### PR TITLE
feat: Implement initial mesh support

### PR DESCRIPTION
**Pull request by manzt**
Implements initial support for meshes. See `./examples/mesh_layers.ipynb` for an example. It is based on the corresponding [JavaScript demo](https://niivue.github.io/niivue/features/mesh.layers.html).

### CODE REVIEW

**Comment by manzt** [comment]
TODO: I don't see any visual changes adjusting `mesh[0].opacity = <new value>` or `mesh[0].visibile = False`.

**Comment by christian-oreilly** [comment]
Great to see that this feature is moving forward! I fetched the branch and tried the mesh_layer.ipynb notebooks and it runs without issues but do not display any output

image

This behavior is on VS Code in MacOS.

**Comment by kolibril13** [comment]
hi @christian-oreilly , I just ran this script as well on MacOS in VS Code, and it runs correctly:
image
Did you run `npm run dev` before executing the notebook?

**Comment by christian-oreilly** [comment]
I had not. I had run `npm run build`. I did not know that `npm run dev` was necessary since I was not modifying the JS myself. In any case, I did now and it did not change anything. I also check with the normal Jupyter Notebook and JupyterLab and it also does not work there. I got a screenshot of the JS console when I run that cell:

image

Not sure if that can be useful to you. I'll be traveling for the next 3 weeks or so, so I may not be able to follow up on this before I return, but I wanted to share this before leaving.

**Comment by manzt** [comment]
> I had not. I had run npm run build. I did not know that npm run dev was necessary since I was not modifying the JS myself. 

To clarify, the front-end source code is in TypeScript and requires transformation to load in the browser. The final assets are not checked into source control, so trying out new changes requires running a `npm run build` step.

When publishing to PyPI, we build the files for others much like distributing wheels so others do not need to "compile" themselves"

**Comment by manzt** [comment]
I'm going to merge to continue iteration. This PR also introduces better typesafety and code quality to the code base so I don't want to be blocked with that. @christian-oreilly when you are back ping me and we can find a time for you to try out the changes.

**Pull request merged**
