### PR TITLE
Use niivue in side panel

### PR DESCRIPTION
**Pull request by kolibril13**
This is a utility notebook to use niivue like this:
The notebook will stay static, while the niivue viewer is always at the same position on the right side:
image

### CODE REVIEW

**Comment by kolibril13** [comment]
this is not priority right now, so I'm converting this one to stale.

**Comment by christian-oreilly** [comment]
@kolibril13 Any reason not to merge this one in? Is it incomplete or is it functioning and could be merged?

**Comment by kolibril13** [comment]
It's complete and can be merged.
Note that ipylab itself has a small issue on Mac when opening in splitview:
https://github.com/jtpio/ipylab/issues/142

**Review by bcalford — APPROVED** [review]
As noted, there can be some issues with opening split view on Mac. However, there is nothing we can do about this for this project. Moving the split view of the NiiVue instance seems to fix the issue of it not showing up.

**Pull request merged**
